// flow-typed signature: ba59f32c5e00900875149f48309c8d8b
// flow-typed version: <<STUB>>/esprima_v4.x.x/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'esprima'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'esprima' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'esprima/bin/esparse' {
  declare module.exports: any;
}

declare module 'esprima/bin/esvalidate' {
  declare module.exports: any;
}

declare module 'esprima/dist/esprima' {
  declare module.exports: any;
}

// Filename aliases
declare module 'esprima/bin/esparse.js' {
  declare module.exports: $Exports<'esprima/bin/esparse'>;
}
declare module 'esprima/bin/esvalidate.js' {
  declare module.exports: $Exports<'esprima/bin/esvalidate'>;
}
declare module 'esprima/dist/esprima.js' {
  declare module.exports: $Exports<'esprima/dist/esprima'>;
}
