// flow-typed signature: eddf913f886fd289968e814e7a0b04a8
// flow-typed version: <<STUB>>/shaven_v1.2.0/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'shaven'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'shaven' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'shaven/build/browser' {
  declare module.exports: any;
}

declare module 'shaven/build/buildTransformString' {
  declare module.exports: any;
}

declare module 'shaven/build/defaults' {
  declare module.exports: any;
}

declare module 'shaven/build/escape' {
  declare module.exports: any;
}

declare module 'shaven/build/mapAttributeValue' {
  declare module.exports: any;
}

declare module 'shaven/build/namespaceToURL' {
  declare module.exports: any;
}

declare module 'shaven/build/parseSugarString' {
  declare module.exports: any;
}

declare module 'shaven/build/server' {
  declare module.exports: any;
}

declare module 'shaven/build/stringifyStyleObject' {
  declare module.exports: any;
}

declare module 'shaven/shaven' {
  declare module.exports: any;
}

declare module 'shaven/shaven.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'shaven/build/browser.js' {
  declare module.exports: $Exports<'shaven/build/browser'>;
}
declare module 'shaven/build/buildTransformString.js' {
  declare module.exports: $Exports<'shaven/build/buildTransformString'>;
}
declare module 'shaven/build/defaults.js' {
  declare module.exports: $Exports<'shaven/build/defaults'>;
}
declare module 'shaven/build/escape.js' {
  declare module.exports: $Exports<'shaven/build/escape'>;
}
declare module 'shaven/build/mapAttributeValue.js' {
  declare module.exports: $Exports<'shaven/build/mapAttributeValue'>;
}
declare module 'shaven/build/namespaceToURL.js' {
  declare module.exports: $Exports<'shaven/build/namespaceToURL'>;
}
declare module 'shaven/build/parseSugarString.js' {
  declare module.exports: $Exports<'shaven/build/parseSugarString'>;
}
declare module 'shaven/build/server.js' {
  declare module.exports: $Exports<'shaven/build/server'>;
}
declare module 'shaven/build/stringifyStyleObject.js' {
  declare module.exports: $Exports<'shaven/build/stringifyStyleObject'>;
}
declare module 'shaven/shaven.js' {
  declare module.exports: $Exports<'shaven/shaven'>;
}
declare module 'shaven/shaven.min.js' {
  declare module.exports: $Exports<'shaven/shaven.min'>;
}
