// flow-typed signature: 8dae4993de5ef10ec3556f13b0464cc1
// flow-typed version: <<STUB>>/whatwg-url_v^6.4.0/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'whatwg-url'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'whatwg-url' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'whatwg-url/lib/infra' {
  declare module.exports: any;
}

declare module 'whatwg-url/lib/public-api' {
  declare module.exports: any;
}

declare module 'whatwg-url/lib/URL-impl' {
  declare module.exports: any;
}

declare module 'whatwg-url/lib/url-state-machine' {
  declare module.exports: any;
}

declare module 'whatwg-url/lib/URL' {
  declare module.exports: any;
}

declare module 'whatwg-url/lib/urlencoded' {
  declare module.exports: any;
}

declare module 'whatwg-url/lib/URLSearchParams-impl' {
  declare module.exports: any;
}

declare module 'whatwg-url/lib/URLSearchParams' {
  declare module.exports: any;
}

declare module 'whatwg-url/lib/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'whatwg-url/lib/infra.js' {
  declare module.exports: $Exports<'whatwg-url/lib/infra'>;
}
declare module 'whatwg-url/lib/public-api.js' {
  declare module.exports: $Exports<'whatwg-url/lib/public-api'>;
}
declare module 'whatwg-url/lib/URL-impl.js' {
  declare module.exports: $Exports<'whatwg-url/lib/URL-impl'>;
}
declare module 'whatwg-url/lib/url-state-machine.js' {
  declare module.exports: $Exports<'whatwg-url/lib/url-state-machine'>;
}
declare module 'whatwg-url/lib/URL.js' {
  declare module.exports: $Exports<'whatwg-url/lib/URL'>;
}
declare module 'whatwg-url/lib/urlencoded.js' {
  declare module.exports: $Exports<'whatwg-url/lib/urlencoded'>;
}
declare module 'whatwg-url/lib/URLSearchParams-impl.js' {
  declare module.exports: $Exports<'whatwg-url/lib/URLSearchParams-impl'>;
}
declare module 'whatwg-url/lib/URLSearchParams.js' {
  declare module.exports: $Exports<'whatwg-url/lib/URLSearchParams'>;
}
declare module 'whatwg-url/lib/utils.js' {
  declare module.exports: $Exports<'whatwg-url/lib/utils'>;
}
